_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
clip_coef:
    value: 0.2
ent_coef:
    value: 0.05
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
max_length:
    value: 13
num_episodes:
    value: 10000
